package sampleeovo.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 26 13:59:04 PST 2019
// ---------------------------------------------------------------------
public interface SampleAppModule extends ApplicationModule {
    String createEmployeeRow();
}

