package sampleeovo.model;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ApplicationModuleImpl;

import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import sampleeovo.model.common.SampleAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 24 14:35:25 PST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SampleAppModuleImpl extends ApplicationModuleImpl implements SampleAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public SampleAppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public EmployeesVOImpl getEmployeesVO1() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public EmployeesVOImpl getEmployeesVO2() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO2");
    }
    public String createEmployeeRow(){
        try{
        ViewObject employeeVO1 = this.getEmployeesVO1();
        Row employeeRow=employeeVO1.createRow();
        
//       employeeRow.setAttribute("FirstName","Sadhana");
//        employeeRow.setAttribute("EmployeeId",10000);
//        employeeRow.setAttribute("LastName","From Andhra");
//        employeeRow.setAttribute("Email","paladugu@gmail");
//        employeeRow.setAttribute("JobId",50);
//       employeeRow.setAttribute("HireDate",new Timestamp());
//        employeeVO1.insertRow(employeeRow);
        }catch(Exception e){
            System.out.println("Exception occured while creating new row"+e);
        }
    return "";
    }
    public String saveEmployeeRow(){
        try{
            getDBTransaction().commit();
        }
        catch(Exception e) {
                                 System.out.println("Exception"+e);
                                 
                             }return null;
        }

    /**
     * Container's getter for DepartmentsEOView1.
     * @return DepartmentsEOView1
     */
    public ViewObjectImpl getDepartmentsEOView1() {
        return (ViewObjectImpl) findViewObject("DepartmentsEOView1");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public EmployeesVOImpl getEmployeesVO3() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for EmployeesVO4.
     * @return EmployeesVO4
     */
    public EmployeesVOImpl getEmployeesVO4() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO4");
    }

    /**
     * Container's getter for DepartmentsEOView2.
     * @return DepartmentsEOView2
     */
    public ViewObjectImpl getDepartmentsEOView2() {
        return (ViewObjectImpl) findViewObject("DepartmentsEOView2");
    }

    /**
     * Container's getter for EmpDeptFkLink.
     * @return EmpDeptFkLink
     */
    public ViewLinkImpl getEmpDeptFkLink() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink");
    }

    /**
     * Container's getter for DeptMgrFkLink.
     * @return DeptMgrFkLink
     */
    public ViewLinkImpl getDeptMgrFkLink() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink");
    }
}


