package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 17:19:56 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String searchEmployee(String employeeID);
}

