package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 09 21:24:23 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {

    String createEmployeeRow();

    String saveEmployeeRow();

    String createEmployeeRow1();

    String saveEmployeeRow1();

    String SearchEmployee(Integer employeeID);
}

