package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 07 02:29:44 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApplicationModuleImpl extends oracle.jbo.server.ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApplicationModuleImpl() {
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl) findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public DepartmentsVOImpl getDepartmentsVO1() {
        return (DepartmentsVOImpl) findViewObject("DepartmentsVO1");
    }
}

