package demo.model;

import demo.model.common.AppModule;

import oracle.adf.model.BindingContext;
import oracle.adf.model.OperationBinding;
import oracle.adf.model.binding.DCBindingContainer;


import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 02 13:28:26 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl) findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl) findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmpManagerFkLink.
     * @return EmpManagerFkLink
     */
    public ViewLinkImpl getEmpManagerFkLink() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink");
    }
    public String createEmployeeRow(){
      
     System.out.println("Creation of new row for ADF employee table inside create Employee Row");
        try{
        ViewObject employeeVO1 = this.getEmployeesView1();
        Row employeeRow=employeeVO1.createRow();
        employeeVO1.insertRow(employeeRow);
     //     employeeRow.setAttribute("FirstName","Sadhana");
    //     employeeRow.setAttribute("EmployeeId",10000);
    //  employeeRow.setAttribute("LastName","From Andhra");
    // employeeRow.setAttribute("Email","paladugu@gmail");
    //   employeeRow.setAttribute("JobId",50);
    //  employeeRow.setAttribute("HireDate",new Timestamp());
    //   employeeVO1.insertRow(employeeRow);
        }catch(Exception e){
            System.out.println("Exception occured while creating new row"+e);
        }
    return "";
    }
}

