package demo.model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 02 13:33:39 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesDefImpl() {
    }
}

