package demo.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 02 14:47:31 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String createEmployeeRow();
}

